language: ruby
rvm:
- 2.1
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: w8MMjs0PiR//+ml2cb+Ms7RSh8w/100wSJB6bPvGhS50DfbVVn6ByrfYwsAzd0MbVkVu3SBV4vvyaWQBTrxelJ4w4c2aRS7L0hOJKRtJl2Y02++OvkWiZbn6N/n/H72dCCHIRTvLtnta06jFFJNCqBLPtZJN2xL1C0RJa0HdQImtDkjcqQIlD8hofV1WZZB4fEVEChyT/cB9EU/9a3cp8u+lly6ebGa7wUqaaTkmXBSMrq2ZiXhiZ931GR3ohmoQrEK+f6WIT2zyMWLnxvx1fbgY6TyanidbvAUz/L6rb32BY7bdGC+QvQXL8vFCgb66SXSXq9/jNjnJ64DEpnRGVvnoni/nsJrioL8pjxTv/ffG9m9xCgKDIVaWxh9JtxCnurJotYV9qH81ZgJEGSaKKowAwvuXpCGDkg8EwJHacmXTAeF27cynHxUcTRzrG/qFD9Wh8olOlUqw0tWIE6ByXLo9FkIXti/g4Q57d+CxLlJcPZkQkkDJGvjbjvYw2N01QyM69sms3RRFmLMkM3UiLUmYOFl9aKWJ6gMKF/MP2YLV6LwvaDY+DwMO9JuJPx9ZZgFXlq44Qz4QJlZSuHLiPWPeP41yn3CwsaPYg7xMv8vkAXLP1N+LOJ3yVIgjt247tcTWonx1ne9p1TrAknzcic73u1Zcz0nQkNKXmUSbd4w=
